// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"

	"github.com/alecthomas/types/optional"
)

type Challenge struct {
	Pk          int64
	ID          string
	Challenge   string
	DateCreated time.Time
}

type Dap struct {
	Pk          int64
	ID          string
	Did         string
	Handle      string
	Proof       optional.Option[string]
	DateCreated string
}
